### ISSUE TITLE
Replace with inline regex variables not working

### ISSUE THREAD

**Issue by RichardLitt** [lazd/gulp-replace#25]
I'm trying to use this line: `    .pipe(replace(/^(.*)(\r?\n\1)+$/g, '$1'))`, And I'm not getting the expected result. On an example file of: 

```
foo
foo
foo
```

It should return a file of `foo`. Thoughts?

**Comment by lazd** [comment]
@RichardLitt did you ever figure out the source of this problem?

**Comment by RichardLitt** [comment]
I didn't. If no one else has had this issue recently, I'd close this.

**Comment by lazd** [comment]
@RichardLitt if we can still reproduce this, it should at least be documented, though, this sounds like a confusing behavior.

**Comment by RichardLitt** [comment]
Still getting it. https://github.com/RichardLitt/regex-find-unique-xml-things

**Comment by lazd** [comment]
:( Let's figure this out, it's probably something simple we're missing here.

**Comment by RichardLitt** [comment]
Alright, I'll look into it some more when I get some free time this week.

**Comment by RichardLitt** [comment]
...I just tried again. I've still got no idea. It's got something to do with global match not working, I think. Different environments may do indexing differently. Another possibility is that we should be using a new Regexp object, not just the `/regex/` thing. See [here](http://stackoverflow.com/questions/432493/how-do-you-access-the-matched-groups-in-a-javascript-regular-expression#comment16270502_432503)

**Comment by davidtheclark** [comment]
@RichardLitt and @lazd: I tried looking into this. In the end, I'm not sure there's really a problem (?) unless @RichardLitt you can give a more simple example demonstrating where things go wrong. Here are some things I found:

I created a test based on the initial reported problem --- that
```
foo
foo
foo
```
didn't return the expected
```
foo
```
with the call `replace(/^(.*)(\r?\n\1)+$/g, '$1')`.

```js
it.only('should work with inline regex variable', function() {
  var file = new gutil.File({
    path: 'test/fixtures/foo.txt',
    cwd: 'test/',
    base: 'text/fixtures',
    contents: fs.readFileSync('test/fixtures/foo.txt')
  });

  var stream = replacePlugin('/^(.*)(\r?\n\1)+$/g', '$1');
  stream.on('data', function(newFile) {
    should.exist(newFile);
    should.exist(newFile.contents);

    newFile.contents.pipe(es.wait(function(err, data) {
      should.not.exist(err);
      data.should.equal(fs.readFileSync('test/expected/foo.txt', 'utf8'));
      done();
    }));
  });
});
```
This test passed just fine --- suggesting that the plugin is in fact working as expected, right?

Also, I looked at the `regex-find-unique-xml-things` repo to see what's going on, and there are a few reasons I don't think it is a clear enough test case:
- The input is piped through 4 replacements. @RichardLitt do you know that everything works as expected up until the final call?
- I'd expect not, because I don't think `new RegExp('.*Loop="([A-Za-z ]*)".*\n',"g")` is really what you want. If you create a RegExp object passing a string for the pattern, you have to escape every special character (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp). So I think there's a good chance that *that* step is not working as expected. Make sense?

@RichardLitt I'd make sure that each regex you're using, tested independently, does exactly what you expect them to do; then you can identify which step is going wrong.

I hope this helps, and I'm not missing something important.

**Comment by RichardLitt** [comment]
Thanks, @davidtheclark. I knew that there were 4 replacements - I knew that they all work up to that line. I've just gone through and made a simple example (https://github.com/RichardLitt/regex-find-unique-xml-things). Now it fails to convert 

```
cat
cat
cat
```
to
```
cat
```
Not sure why. :/

**Comment by RichardLitt** [comment]
Again, it works on Sublime. So - maybe Sublime is messing up something here, too. I don't know.

**Comment by davidtheclark** [comment]
Thanks, I was able to clone that repo and reproduce the issue!

Figured out the problem I think. Sublime must be doing a multiline regex by default (?), or something; but that's not the case in JS. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#boundaries will tell you that the `^` and `&` characters you were using, *intending* them to mean "start of line" and "end of line", were *actually* meaning "start of input" and "end of input".

In order go what you intend, you can either use the multiline flag `m`, or just remove the `^` and `$` characters (since you're already checking for line breaks, do you need them?).

Does that solve the issue for you @RichardLitt? It worked for me in your repo.

**Comment by RichardLitt** [comment]
I do believe you've got it. That's awesome. Thank you, @davidtheclark!

Since this is in fact an issue with Sublime automatically doing something, this isn't an issue with gulp-replace. I think this can be closed.

**Comment by lazd** [comment]
@davidtheclark, thank you for jumping in and helping @RichardLitt figure this one out!
