### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by ahumphreys87** [lazd/gulp-replace#35]
Hi

Using 0.5.1 has broken our build, we get issues surrounding the istextorbinary dependency. I have tested  against the master branch of the this repo and all seems fine. Is there any chance you could release a patch version to fix this?

I've fixed the issue in our build by specifically pulling in 0.5.0 for now but would be great if we could keep up to date with the latest.

Thanks

**Comment by lazd** [comment]
Probably duplicates #33, can you try `npm remove gulp-replace; npm install gulp-replace`? In any case, you need to paste output to show what these "issues surrounding istextorbinary" are otherwise I'm stabbing in the dark.

The only thing that changed between 0.5.0 and 0.5.1 was hard coding the istextorbinary dependency version to 1.0.0 as 1.0.1 was released with no code.

**Comment by lazd** [comment]
@ahumphreys87, I'm going to close this issue as I've verified 0.5.1 works correctly. Please let me know if you're unable to fix it.
