### ISSUE TITLE
wth is this

### ISSUE THREAD

**Issue by ORESoftware** [lazd/gulp-replace#55]
sorry, but WTH is this

/Users/amills001c/WebstormProjects/ORESoftware/sc-admin-ui-express/node_modules/gulp-replace/index.js:9
    if (file.isNull()) {    <=====

TypeError: undefined is not a function

**Comment by lazd** [comment]
Please use respect when reporting issues.

You have provided no details whatsoever as to your setup. What version of gulp are you using? How is your gulpfile configured?

**Comment by ORESoftware** [comment]
I gave up on your lib quickly and I can't remember what this was

but if file is null, then calling isNull on a null will result in TypeError. 

I don't know what your isNull function is supposed to do but normally we check for nulls like so

if(file == null)

right? what am I missing?

all the info you need is in the original message I sent, I can't remember what I send your lib, but the error message I got was indicative of a lib that didn't handle its inputs correctly.

also, steaming APIs are not standardized yet and this is posing a lot of problems so it's not exactly your fault. sorry for being rude.

**Comment by lazd** [comment]
This is a common pattern used in many other gulp plugins:

* [gulp-sass](https://github.com/dlmanning/gulp-sass/blob/master/index.js#L22-L24)
* [gulp-concat](https://github.com/wearefractal/gulp-concat/blob/master/index.js#L39-L42) (from wearefractal, gulp's creator)

Next time, [try Googling instead of being a dick](http://stackoverflow.com/questions/27366098/gulp-object-file-has-no-method-isnull). gulp 3.0.0 doesn't seem to have the `isNull` methods on its file object. Since you failed to provide the version of gulp you're using, I can assume this was your problem as well.

Good luck.
