### ISSUE TITLE
String replacement inside SCSS partials

### ISSUE THREAD

**Issue by rbfonbuena** [lazd/gulp-replace#98]
Not sure if this is a gulp-replace or gulp-sass issue, but for some reason strings inside partials are not being replaced. I've created a test repo at https://github.com/rbfonbuena/gulp-replace-test

TIA

**Comment by SockFuzz** [comment]
It has been a while since this issue was raised but if you are still available can you advise if the issue you were receiving was similar to the issue I just posted on stackoverflow here?

[https://stackoverflow.com/questions/60348119/gulp-replace-regex-removing-more-characters-than-specified-in-the-regex-string](https://stackoverflow.com/questions/60348119/gulp-replace-regex-removing-more-characters-than-specified-in-the-regex-string)

**Comment by jnhghy** [comment]
Both links are 404 not found now

**Comment by lazd** [comment]
I can almost guarantee this is user error. Regex is hard. If there's still something wrong, please re-open with a complete example.
